name: Build Windows Executable

on:
  push:
    branches: [ main ]  # 只在 main 分支推送时触发
  workflow_dispatch:    # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest  # 仅使用 Windows 环境

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 安装依赖
      run: |
        pip install pyinstaller
        # 安装你的脚本依赖（按需修改）
        pip install requests

    - name: 打包可执行文件
      run: |
        pyinstaller --onefile --noconsole your_script.py
        # 参数说明：
        # --onefile    : 生成单个exe文件
        # --noconsole  : 运行时不显示控制台窗口（GUI程序用）
        # --icon=icon.ico : 添加图标（可选）
        # --add-data "data;data" : 添加资源文件夹（可选）

    - name: 上传成品
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/  # 打包文件所在目录
